package org.avirtuos.teslog.api.streaming;


/**
 * Defines a source of streaming telemetry data which other classes.
 */
public interface TelemetryStream {

    /**
     * Used to subscribe to the stream of TelemetryMessages generated by this TelemetryStream.
     * @param listener The listener to delegate TelemetryEvents to.
     * @throws RuntimeException If there is already a subscriber with the same id subscribed.
     * @note The id of the listener must be unique.
     */
    void subscribe(TelemetryListener listener);

    /**
     * Used to un-subscribe to the stream of TelemetryMessages generated by this TelemetryStream.
     * @param listener The listener to delegate TelemetryEvents to.
     * @throws RuntimeException If there is no current subscription for the id of the provided subscriber.
     */
    void unsubscribe(TelemetryListener listener);

    /**
     * Used to start the TelemetryStream.
     */
    void start();

    /**
     * Used to stop the TelemetryStream.
     */
    void stop();
}
